spring:
  main:
    allow-circular-references: true
  application:
    name: security
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect